title: Kranthi Kumar Nalla
logo: /images/1.jpeg
description: Interior Designer|  I specialize in the transformation of spaces into functional and aesthetically pleasing environments | Civil Engineer 🚀📊
#show_downloads: true
#email: kranthikumarnalla@outlook.com
#location: India
theme: jekyll-theme-minimal
