title: Sai Swaroop Gali
logo: /assets/Profile.png
description: Data Alchemist | Bridging the Gap Between Data and Value | AWS Certified Cloud Practitioner 🚀📊
#show_downloads: true
#email: Sai-Swaroop.Gali@outlook.com
#location: Emden, Germany
theme: jekyll-theme-minimal
