title: Kranthi Kumar Nalla
logo: /images/1.jpeg

description: Interior Designer|Civil Engineer 🚀📊

#show_downloads: true
#email: kranthikumarnalla@outlook.com
#location: India


theme: jekyll-theme-minimal
